version: "3.9"
services:
    mysql:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
